### ISSUE TITLE
Add Contributing.md file for this repository.

### ISSUE THREAD

**Issue by ashishrana160796** [DeepVisionCentre/deepvisioncentre.github.io#3]
This is a beginner only issue.
Please, read Contributing.md [here](https://github.com/DeepVisionCentre/DeepVisionTool/blob/master/Contributing.md).
Please, copy Contributing.md from [DeepVisionTool](https://github.com/DeepVisionCentre/DeepVisionTool) and make a PR.
All the best !!

**Comment by Haugum** [comment]
Hi @ashishrana160796 , can I be added as a contributor so I may push my commit and submit a PR?

**Comment by GOVINDDIXIT** [comment]
working

**Comment by Haugum** [comment]
PR submitted.
